/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_androidtest_six_JNIUtils */

#ifndef _Included_com_example_administrator_androidtest_six_JNIUtils
#define _Included_com_example_administrator_androidtest_six_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_androidtest_six_JNIUtils
 * Method:    sayHelloFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_androidtest_1six_JNIUtils_sayHelloFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
